_ostree.py: Fix string formatting in fetch()
New-style formatting does not implicitly convert from float to int. Add
explicit conversion to fix the following error:

	ValueError: Unknown format code 'd' for object of type 'float'

Fixes: 3b17762a ("Switch old-style string formattings to new...")