element: Give a helpful error if the 'collect' dir doesn't exist
This can occur with 'script' elements for example where the 'collect'
directory can be specified by the user.

Previously putting an invalid directory for the 'collect' field caused
this output:

    [--:--:--][7ea949f2][initramfs/initramfs-gz.bst         ] START   Caching Artifact
    [00:03:09][7ea949f2][initramfs/initramfs-gz.bst         ] BUG     gnu-toolchain/initramfs-initramfs-gz/7ea949f2-build.4045.log

        An unhandled exception occured:

        Traceback (most recent call last):
          File "/home/shared/src/buildstream/buildstream/_scheduler.py", line 643, in child_action
            result = self.action(element)
          File "/home/shared/src/buildstream/buildstream/_pipeline.py", line 152, in process
            element._assemble()
          File "/home/shared/src/buildstream/buildstream/element.py", line 715, in _assemble
            self.__artifacts.commit(self, collectdir)
          File "/home/shared/src/buildstream/buildstream/_artifactcache.py", line 136, in commit
            _ostree.commit(self.repo, content, ref)
          File "/home/shared/src/buildstream/buildstream/_ostree.py", line 138, in commit
            mtree, commit_modifier)
        GLib.GError: g-io-error-quark: openat: No such file or directory (1)

    Build failure on element: initramfs/initramfs-gz.bst

One now gets a more useful error:

    [00:02:55] FAILURE [initramfs/initramfs-gz.bst]: Build

        Directory '/invalid' was not found inside the sandbox, unable to collect artifact contents